### PR TITLE
[#8] Remove channel name argument from changeChannel method

### LINKED ISSUE #8: Remove channel name argument from changeChannel method
The channel name is the channel identified, so the name argument is unneeded for this method since the new channel passed as argument is enough to do the modification

### PR DESCRIPTION
**Pull request by yersan**
fixes #8

CC @spyrkob FYI

### CODE REVIEW

**Comment by spyrkob** [comment]
@yersan to confirm, following would result in an error:
 * if the channel has no name defined
 * if a channel name doesn't match any already present channels

**Comment by yersan** [comment]
@spyrkob that sounds correct to me too.

**Comment by spyrkob** [comment]
is it worth adding it to the javadoc description?

**Comment by spyrkob** [comment]
is it worth adding this to the method's javadoc?

**Comment by yersan** [comment]
Ideally, yes, since it is an API, although only used by two pieces at the moment

**Comment by yersan** [comment]
@spyrkob ^^^

**Review by spyrkob — APPROVED** [review]

**Pull request merged**
